
version: 2.1

jobs:
  build:
    docker:
      - image: themattrix/tox-base

    environment:
      # prevent *.pyc files
      PYTHONDONTWRITEBYTECODE: 1

    steps:
      - checkout
      - run:
          name: Install git and mercurial
          command: |
            apt-get update
            apt-get install -y git-core
            apt-get install -y mercurial
            git config --global user.email "bumpversion_test@example.org"
            git config --global user.name "Bumpversion Test"
      - run:
          name: Update pyenv
          # to access newer Python releases.
          command: |
            cd /.pyenv
            git fetch
            git checkout v1.2.15
      - run:
          name: Install python interpreters
          command: |
            pyenv versions
            # for the list of pre-installed Python versions in the docker image,
            # see https://github.com/themattrix/docker-tox-base/blob/master/python-versions.txt
            pyenv global system 2.7.17 3.5.7 3.6.9 3.7.5 pypy2.7-7.2.0 pypy3.6-7.2.0

      - run:
          name: Run tests
          command: tox
