
version: 2.1

jobs:
    build:
        docker:
            - image: themattrix/tox-base

        steps:
            - checkout
            - run: apt-get update && apt-get install -y git-core mercurial
            - run: cd /.pyenv && git fetch && git checkout v1.2.8
            - run: git --version
            - run: hg --version
