
version: 2.1

jobs:
    build:
        docker:
            - image: themattrix/tox-base

        steps:
            - checkout
            - run: git --version
            - run: mercurial --version
